settings:
  title: 'Sunucu/Site Durum Bilgisi'
  url: 'https://status2.bariskeser.com' # used for Slack messages
  logo: logos.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Tüm Siteler Olması Gerektiği Gibi Çalışıyor'
  notAllmonitorsOperational: 'Tüm Siteler Yanıt Vermiyor'
  monitorLabelOperational: 'Tekrar Aktif Oldu'
  monitorLabelNotOperational: 'Zaman Aşımına Uğradı'
  monitorLabelNoData: 'Veri yok'
  dayInHistogramNoData: 'Veri yok'
  dayInHistogramOperational: 'Düzgün olarak Çalışıyorlar'
  dayInHistogramNotOperational: ' proglem(ler)' # xx incident(s) recorded

monitors:
  - id: bariskeser-com # unique identifier
    name: bariskeser.com
    description: 'Kendi Sitem' # default=empty
    url: 'https://bariskeser.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true