settings:
  title: 'Sunucu Durumu'
  url: 'https://status.bariskeser.com' # used for Slack messages
  logo: logos.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Tüm Sistemler Operasyonel'
  notAllmonitorsOperational: 'Tüm Sistemler Çalışmıyor'
  monitorLabelOperational: 'Operasyonel'
  monitorLabelNotOperational: 'Operasyonel Değil'
  monitorLabelNoData: 'Veri yok'
  dayInHistogramNoData: 'Veri yok'
  dayInHistogramOperational: 'Hepsi iyi'
  dayInHistogramNotOperational: ' olay(lar)' # xx incident(s) recorded

monitors:
  - id: bariskeser-com # unique identifier
    name: bariskeser.com
    description: 'Kendi Sitem' # default=empty
    url: 'https://bariskeser.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: cumicbot-tk
    name: cumicbot.tk
    description: 'Bot Websitesi'
    url: 'https:///cumicbot.tk'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: eronalist-com
    name: eronalist.com
    description: 'Eren Arkadaşımızın sitesi'
    url: 'https:///eronalist.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
