name = "status"
workers_dev = true
account_id = "278af70e005da2b9dad665f4340a2797"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["*/5 * * * *"]

[site]
bucket = "out"
main = "workers-site/index.js"
